name: Minify JSON

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Minify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install -g json-minify

    - name: Minify JSON files
      run: |
        for file in $(find . -type f -name '*.json' | grep -v '\.min\.json'); do
          echo "$file"
          json-minify "$file" > "${file%.json}.min.json"
        done

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add *.min.json
        git commit -m "Minify JSON files"
        git push
